version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: homematicip
    versions:
    - 0.13.0.post0.dev3
    - 0.13.1.post0.dev4
    - 1.0.0
  - dependency-name: datadog
    versions:
    - 0.39.0
    - 0.40.1
  - dependency-name: pytibber
    versions:
    - 0.16.1
  - dependency-name: httplib2
    versions:
    - 0.18.0
  - dependency-name: pillow
    versions:
    - 6.2.0
  - dependency-name: flake8-docstrings
    versions:
    - 1.5.0
